weather-api:
  port: 80
  uri: https://api.openweathermap.org
  appId: 123

spring:
  data:
    mongodb:
      # TODO set url from mongo DB container
      uri: mongodb://localhost:8989/test

db:
  clear:
    probability:
      percentage: 10